language: php

addons:
  postgresql: "9.5"
  apt:
    packages:
      - openjdk-8-jre

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

# Alternate tests with MySQL and PostgreSQL
matrix:
  include:
    # PHP 7.0
    - php: 7.0
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE NODE_VERSION=14.15.0
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE NODE_VERSION=8.9.0
    # PHP 7.2
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE NODE_VERSION=14.15.0
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE NODE_VERSION=14.15.0
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE NODE_VERSION=14.15.0
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE NODE_VERSION=14.15.0

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3;
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci validate
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat